### ISSUE TITLE
I failed to install this extension

### ISSUE THREAD

**Issue by essesoul** [flarumite/simple-discussion-views#28]
I failed to install this ,with some warnings like : "but it does not match your minimum-stability "

![image](https://user-images.githubusercontent.com/58624474/195285462-bd43ec3f-61c1-4c22-b525-e78ddb13780d.png)

**Comment by luceos** [comment]
Fixed on discuss: https://discuss.flarum.org/d/31219-blomstra-font-awesome-6/25

@essesoul please do not crosspost to draw attention to your problems. One channel would have been more than enough.
